class projectile extends entity{
    constructor(layer,x,y,type){
        super(layer,x,y)
        this.type=type
        this.name=types.projectile[type].name
        this.speed=types.projectile[type].speed
        this.used=false
        this.fade=0
    }
    hit(type){
        switch(type){
            case 0:
                this.used=true
                this.speed=0
            break
        }
    }
    display(){
        this.layer.push()
        this.layer.translate(this.position.x,this.position.y)
        switch(this.name){
        }
        this.layer.pop()
    }
    update(){
        super.update()
        this.fade=smoothAnim(this.fade,!this.used,0,1,5)
        if(this.fade<=0&&this.used){
            this.remove=true
        }
    }
}